RDCC-5815-Common data api - Test coverage with BDD Approach
hmcts/rd-commondata-api pull request #240
Opened 2022-11-18 17:00 UTC by manukundloo-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-5900

### Change description ###
RDCC-5900-Common data api Controller - Test coverage with BDD Approach

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-11-21 10:52 UTC, rajkatla-hmcts requested changes

2022-11-21 12:14 UTC, manukundloo-hmcts commented on src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiControllerTest.java
> +    void testShouldReturn200WhenPassingRightCategoryId() throws Exception {
thank you for the review comment add the displayname annotation before the test case

2022-11-21 12:41 UTC, manukundloo-hmcts commented on src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CaseFlagApiControllerTest.java
> +    void should_return_200_with_all_positive_scenario_flags() throws Exception {
naming convention followed for all test cases

2022-11-21 12:41 UTC, manukundloo-hmcts commented on src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CaseFlagApiControllerTest.java
> +    void should_return_200_with_all_positive_scenario_flags() throws Exception {
display name annotation addd for all test cases

2022-11-21 13:56 UTC, manukundloo-hmcts commented on src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CaseFlagApiControllerTest.java
> +            .andExpect(jsonPath("$.flags[0].FlagDetails[0].flagCode", is(flagCode)))
Added assertion for other fields

2022-11-21 13:56 UTC, manukundloo-hmcts commented on src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CaseFlagApiControllerTest.java
> +
Added assertion for child flag details

2022-11-21 16:11 UTC, manukundloo-hmcts commented on src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiControllerTest.java
> +            .andExpect(jsonPath("$.list_of_values", hasSize(1)));
Added assertion for content and child nodes

2022-11-23 16:30 UTC, rajkatla-hmcts approved these changes

2022-11-23 16:31 UTC, sahitya-desireddy approved these changes

2022-11-28 14:28 UTC, merged