Rdcc 5572 update case flags api
hmcts/rd-commondata-api pull request #250
Opened 2022-12-06 12:00 UTC by vilasshelke-hmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RDCC-5572

### Change description ###

Case Flags : Update the Get Flags API 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-12-13 16:11 UTC, nayeemshaik-hmcts approved these changes
changes looks fine

2022-12-13 23:26 UTC, rajkatla-hmcts requested changes

2022-12-13 23:26 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCaseFlagsIntegrationTest.java
> +                        assertEquals("Test27", childFlag.getNameCy());
add assertions for other fields as well

2022-12-13 23:26 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCaseFlagsIntegrationTest.java
> +        assertEquals(2, response.getFlags().get(0).getFlagDetails().size());
add assertions for response fields

2022-12-13 23:26 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCaseFlagsIntegrationTest.java
> +        assertEquals(1, response.getFlags().get(0).getFlagDetails().size());
add assertions for response fields

2022-12-13 23:26 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCaseFlagsIntegrationTest.java
> +    void shouldReturnSuccessForRetrieveCaseFlagsByServiceIdWithWelshFlagIsN() throws JsonProcessingException {
this test case already covered in line no 198 test method

2022-12-13 23:26 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCaseFlagsIntegrationTest.java
> +
write another scenario to cover both available-external-flag=Y  and welsh-required=Y

2022-12-13 23:26 UTC, rajkatla-hmcts commented on src/functionalTest/java/uk/gov/hmcts/reform/cdapi/CommonDataApiFunctionalTest.java
> +                "service-id=XBBB?available-external-flag=Y&default-status=true"
endpoint not expecting default-status as query param , what's use of this test case ?

2022-12-14 12:03 UTC, vilasshelke-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCaseFlagsIntegrationTest.java
> +            if (flagDetail.getParent()) {
Accommodated the changes

2022-12-14 12:04 UTC, vilasshelke-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCaseFlagsIntegrationTest.java
> +                flagDetail.getChildFlags().forEach(cf -> assertNull(cf.getNameCy()));
@rajkatla-hmcts - This is JSON response only

2022-12-15 10:03 UTC, closed without merging