Rdcc 6237 common data api spring boot upgrade
hmcts/rd-commondata-api pull request #267
Opened 2023-01-30 19:22 UTC by vilasshelke-hmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RDCC-6237

### Change description ###

Common Data API Spring boot upgrade

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-01-31 11:33 UTC, vasthav-patta approved these changes

2023-01-31 13:11 UTC, sahitya-desireddy approved these changes

2023-02-01 16:55 UTC, rajkatla-hmcts requested changes

2023-02-01 16:55 UTC, rajkatla-hmcts commented on src/main/java/uk/gov/hmcts/reform/cdapi/config/SwaggerConfiguration.java
> +            .group("rd-location-ref-api")
incorrect group name

2023-02-02 11:03 UTC, vilasshelke-hmcts commented on src/main/java/uk/gov/hmcts/reform/cdapi/config/SwaggerConfiguration.java
> +            .group("rd-location-ref-api")
corrected

2023-02-14 14:31 UTC, rajkatla-hmcts approved these changes

2023-02-14 14:32 UTC, merged